import { Model, DataTypes } from "sequelize";
import { sequelize } from "../../db";

export class OrderHeader extends Model {
  Order_Number: any;
  Order_Date: any;
  C_Number: any;
  C_CoName: any;
}

OrderHeader.init(
  {
    Order_Number: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    Order_Date: { type: DataTypes.DATEONLY },
    Control_Date: { type: DataTypes.DATEONLY },
    Delivery_Date: { type: DataTypes.DATEONLY },
    Invoice_Date: { type: DataTypes.DATEONLY },
    QB_TransferDate: { type: DataTypes.DATEONLY },
    Delete_Date: { type: DataTypes.DATEONLY },
    Order_Updated: { type: DataTypes.BOOLEAN },
    Order_Type: { type: DataTypes.INTEGER },
    Confirmed: { type: DataTypes.BOOLEAN },
    Reprint_Invoice_Required: { type: DataTypes.BOOLEAN },
    C_Number: DataTypes.INTEGER,
    S_Number: DataTypes.INTEGER,
    Jurisdiction_State: { type: DataTypes.INTEGER, allowNull: true },
    Jurisdiction_County: { type: DataTypes.INTEGER, allowNull: true },
    Jurisdiction_City: { type: DataTypes.INTEGER, allowNull: true },
    AR_C_Number: DataTypes.INTEGER,
    Order_Pricing_Account: { type: DataTypes.INTEGER },
    InventoryPrepaid_CIG: { type: DataTypes.BOOLEAN },
    InventoryPrepaid_OTP: { type: DataTypes.BOOLEAN },
    Route_Number: DataTypes.INTEGER,
    Stop_Number: DataTypes.INTEGER,
    Delivery_ID: DataTypes.SMALLINT,
    Tracking_Number: { type: DataTypes.STRING(255) },
    OtherPricingLevel: { type: DataTypes.SMALLINT },
    Picklist_Printed: { type: DataTypes.BOOLEAN },
    Labels_Printed: { type: DataTypes.BOOLEAN },
    ePickStatus: { type: DataTypes.SMALLINT },
    Reference: { type: DataTypes.STRING(255) },
    Workstation_ID: { type: DataTypes.SMALLINT },
    User_ID: { type: DataTypes.SMALLINT },
    Picker_ID: { type: DataTypes.SMALLINT },
    Checker_ID: { type: DataTypes.SMALLINT },
    Invoice_Number: DataTypes.INTEGER,
    Invoice_Type: DataTypes.SMALLINT,
    P_Number: { type: DataTypes.INTEGER },
    eInvoice: { type: DataTypes.SMALLINT },
    Invoice_Deposit: DataTypes.DECIMAL(18, 0),
    Delivery_Charge: DataTypes.DECIMAL(18, 0),
    Other_Charge: DataTypes.DECIMAL(18, 0),
    Invoice_Total: DataTypes.DECIMAL(18, 0),
    Sales_Taxable: DataTypes.DECIMAL(18, 0),
    Sales_NonTaxable: DataTypes.DECIMAL(18, 0),
    stax_State: DataTypes.DECIMAL(18, 0),
    stax_County: DataTypes.DECIMAL(18, 0),
    stax_City: DataTypes.DECIMAL(18, 0),
    Bundles: DataTypes.INTEGER,
    Totes: DataTypes.INTEGER,
    Cig10: DataTypes.INTEGER,
    Cig20: DataTypes.INTEGER,
    Cig25: DataTypes.INTEGER,
    Cig10tax: DataTypes.DECIMAL(18, 0),
    Cig20tax: DataTypes.DECIMAL(18, 0),
    Cig25tax: DataTypes.DECIMAL(18, 0),
    POS_Cash: DataTypes.DECIMAL(18, 0),
    POS_Check: DataTypes.DECIMAL(18, 0),
    POS_Credit: DataTypes.DECIMAL(18, 0),
    POS_Debit: DataTypes.DECIMAL(18, 0),
    POS_Other: DataTypes.DECIMAL(18, 0),
    POS_House: DataTypes.DECIMAL(18, 0),
    POS_ChangeDue: DataTypes.DECIMAL(18, 0),
    POS_Time: { type: DataTypes.DATE},
    HouseChargeApplied: DataTypes.DECIMAL(19, 4),
    Points: DataTypes.INTEGER,
    Commission_Paid: DataTypes.SMALLINT,
    Commission_Paid_Cust: DataTypes.SMALLINT,
    Total_Weight: DataTypes.DECIMAL(19, 4),
    WarehouseID: DataTypes.SMALLINT,
    Suspend: DataTypes.BOOLEAN,
    Sales01: DataTypes.DECIMAL(19, 4), Sales02: DataTypes.DECIMAL(19, 4), Sales03: DataTypes.DECIMAL(19, 4), Sales04: DataTypes.DECIMAL(19, 4), Sales05: DataTypes.DECIMAL(19, 4), Sales06: DataTypes.DECIMAL(19, 4), Sales07: DataTypes.DECIMAL(19, 4), Sales08: DataTypes.DECIMAL(19, 4), Sales09: DataTypes.DECIMAL(19, 4), Sales10: DataTypes.DECIMAL(19, 4), Sales11: DataTypes.DECIMAL(19, 4), Sales12: DataTypes.DECIMAL(19, 4),
    Taxes01: DataTypes.DECIMAL(19, 4), Taxes02: DataTypes.DECIMAL(19, 4), Taxes03: DataTypes.DECIMAL(19, 4), Taxes04: DataTypes.DECIMAL(19, 4), Taxes05: DataTypes.DECIMAL(19, 4), Taxes06: DataTypes.DECIMAL(19, 4), Taxes07: DataTypes.DECIMAL(19, 4), Taxes08: DataTypes.DECIMAL(19, 4), Taxes09: DataTypes.DECIMAL(19, 4), Taxes10: DataTypes.DECIMAL(19, 4), Taxes11: DataTypes.DECIMAL(19, 4), Taxes12: DataTypes.DECIMAL(19, 4),
    QB_Transfer: DataTypes.BOOLEAN,
    Order_Number_Legacy: DataTypes.INTEGER,
    Invoice_Number_Legacy: DataTypes.INTEGER,
    Order_Deleted: DataTypes.BOOLEAN,
    Delete_Time: { type: DataTypes.DATE },
    Delete_User_Number: DataTypes.INTEGER,
    TaxesOTP_State: DataTypes.DECIMAL(19, 4),
    TaxesOTP_County: DataTypes.DECIMAL(19, 4),
    TaxesOTP_City: DataTypes.DECIMAL(19, 4),
    TaxesCIG_State: DataTypes.DECIMAL(19, 4),
    TaxesCIG_County: DataTypes.DECIMAL(19, 4),
    TaxesCIG_City: DataTypes.DECIMAL(19, 4),
    PrepaidTax_Amount: DataTypes.DECIMAL(19, 4),
    pCash: DataTypes.INTEGER,
    pCheck: DataTypes.INTEGER,
    pCredit: DataTypes.INTEGER,
    pDebit: DataTypes.INTEGER,
    pOther: DataTypes.INTEGER,
    pPaidOut: DataTypes.INTEGER,
    Delivery_Charge_Select: DataTypes.BOOLEAN,
    Other_Charge_Select: DataTypes.BOOLEAN,
    Invoice_Time: { type: DataTypes.DATE},
    Picklist_Time: { type: DataTypes.STRING  },
    Manifest_Printed: DataTypes.BOOLEAN,
    Manifest_Time: { type: DataTypes.DATE },
    CardType_ID_Credit: DataTypes.TINYINT,
    CardType_ID_Debit: DataTypes.TINYINT,
    CardType_ID_Other: DataTypes.TINYINT,
    MergedToOrder: DataTypes.INTEGER,
    Prebook_CreateNew: DataTypes.BOOLEAN,
    Prebook_Prompt: DataTypes.BOOLEAN,
    POS_CardFee: DataTypes.DECIMAL(19, 4),
    POS_PaidOnAccount: DataTypes.DECIMAL(19, 4),
    AssignedToEPickUser: { type: DataTypes.STRING(5), allowNull: true },
    AssignedOnforEPick: { type: DataTypes.DATE, allowNull: true },
    EpickStatusFromPicker: { type: DataTypes.STRING(80), allowNull: true },
    EpickCompletedOn: { type: DataTypes.DATE, allowNull: true },
    OrderedOn: { type: DataTypes.DATE, allowNull: true },
    Order_Source: { type: DataTypes.INTEGER, allowNull: true },

    Disc_Type: {
      type: DataTypes.STRING(15),   // nvarchar(1)
      allowNull: true,
    },

    Disc_Per: {
      type: DataTypes.DECIMAL(18, 2),
      allowNull: true,
    },

    Disc_Amt: {
      type: DataTypes.DECIMAL(18, 2),
      allowNull: true,
    },



  
    // deliverd: { type: DataTypes.BOOLEAN },
    // Delivered: { type: DataTypes.BOOLEAN },
  },
  {
    sequelize,
    tableName: "Order_Header",
    timestamps: false,
    freezeTableName: true,
    
  }
);
