export const General = {
  SUCCESS: "Success",
  FAIL: 'Fail',
  SOMETHING_WENT_WRONG: "Oops! Something went wrong. Please try again later."

};


export const Manager = {
  EMAIL_ALREADY_EXISTS: "Email already exists",
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_EXISTS: "User already exists",
  UPC_NOT_EXIT: "This UPC Number does not exist or the Item may not be active.",
  UPC_NO_ALREADY_EXIT: "UPC Number already exists",
  RECORD_NOT_FOUND: "Record not found",
  PROMOTION_NOT_FOUND: "Promotion not found",
  CONTACT_NOT_FOUND_IN_EDIT: "Contact not found for editing",
  WAREHOUSE_NOT_FOUND: "Warehouse not found",
  SAME_WAREHOUSE_EXIST: "A warehouse with the same details already exists",
  SAME_WAREHOUSE_EXIST_TITLE: "The title already exists",
  PASSWORD_NOT_MATCH: "The entered password does not match the old password.",
  NEW_PASSWORD_SAME_AS_OLD: "The new password cannot be the same as the old password.",
  SLOT_NOT_FOUND: "Slot not found",
  NO_SLOT_BY_ID: "No slots available for this ID.",
  NO_RECORD_FOUND: "No record found for the given item number.",
  EMAIL_EXITS: "The email is already exists",
  NAME_EXITS: "The username already exists",
  CUSTOMER_NOT_FOUND: "Could not find this Customer",
  USER_EXITS: "The username already exists",
  CUSTOMER_EXITS: "The customer already exists.",
  USER_NOT_FOUND_ALREADY_DELETED: "User not found or already deleted",
  RROUTR_ARE_ASSIGNED: "Routes are assigned to the driver. Please unassign the route before deleting the driver",
  PURCHASE_ORDER_NO_NOT_FOUND: "Purchase Order Number not found",
  UNABLE_TO_DELETE_PO: "Unable to Delete Posted PO",
  ERROR_IN_PO: "An error occurred while deleting the PO",
  FAIL_IN_PURCHASE_ORDER: "Failed to save Purchase Order.",
  VENDOR_NOT_FOUND: "Vendor not found",
  PO_NOT_FOUND: "PO not found",
  SAVED_NOT_FOUND: "Saved Items Not found for this PO, Please add Items and Save.",
  ERROR_IN_RECEVING_PO: "Error occurred while receiving PO items.",
  RECEIVED_ITEM_NOT_IN_PO: "Received Items Not found for this PO, Please save Items and Receive.",
  ERROR_IN_RESETTING: "Error occurred while resetting received quantities",
  PO_SUCCESS_ORDER_HAVE_NOT_RECEIVED: "Purchase order created successfully. Some items in the purchase order have not been received. Would you like to create a back-order for them?",
  PO_SUCCESS: "Purchase order created successfully.",
  NO_RECEIVED_IN_BACKORDER: "No non-received items found for backorder.",
  BACK_ORDER_NOT_FOUND: "Back-order creation failed:",
  WR_IMAGE_EXIST: "Warehouse Image Already Exist.",
  ERROR_IN_WR_IMAGE: "Error in Warehouse image ",
  OTHER_OPTION_NOT_FOUND: "Other option not found",
  DRIVER_ALREADY_ASSIGN: "Driver is already assigned for this day.",
  BANNER_CREATE_SUCCESFULLY: "Banner Uploaded Successfully",
  UPDATE_SUCCESSFULLY_DEVICE_STATUS: "Device Status Updated Successfully",
  PRODUCT_IMAGE_UPLOADED: "Product Image Uploaded Successfully",
  BANNER_UPDATE_SUCCESFULLY: "Banner Updated Successfully",
  BANNER_DELETE_SUCCESFULLY: "Banner Deleted Successfully",
  BANNER_LIST_SUCCESFULLY: "Banner List Successfully",
  FETCH_AR_LIST_SUCCESS: "Account receivables list fetched successfully.",
  FETCH_VENDOR_LIST_SUCCESS: "Vendor list fetched successfully.",
  FETCH_ERP_USER_LIST_SUCCESS: "Erp User list fetched successfully",
  PRODUCT_FETCHED_SUCCESSFULLY: "Product fetched successfully",
  PRODUCT_NOT_FOUND: "Product not found",
  WAREHOUSE_SETTING_UPDATED: "Warehouse setting updated successfully",
  WAREHOUSE_SETTING_FETCHED: "Warehouse setting flags fetched successfully",
  WAREHOUSE_IMAGE_UPLOADED: "Warehouse image uploaded successfully",
  FETCH_AR_TOTALS_SUCCESS: 'Account Receivable Totals fetched successfully',
  WAREHOUSE_CONTACT_DETAILS_FETCHED: "Warehouse contact details fetched successfully",
  // ItemLimit messages
  ITEM_LIMIT_CREATED_SUCCESSFULLY: "Item limit created successfully",
  ITEM_LIMIT_UPDATED_SUCCESSFULLY: "Item limit updated successfully",
  ITEM_LIMIT_DELETED_SUCCESSFULLY: "Item limit deleted successfully",
  ITEM_LIMIT_FETCHED_SUCCESSFULLY: "Item limit fetched successfully",
  ITEM_LIMIT_LIST_FETCHED_SUCCESSFULLY: "Item limit list fetched successfully",
  ITEM_LIMIT_NOT_FOUND: "Item limit not found",
  ITEM_LIMIT_ALREADY_EXISTS: "Item limit already exists for this item number",
  // Link messages
  LINK_CREATED_SUCCESSFULLY: "Link created successfully",
  LINK_UPDATED_SUCCESSFULLY: "Link updated successfully",
  LINK_DELETED_SUCCESSFULLY: "Link deleted successfully",
  LINK_FETCHED_SUCCESSFULLY: "Link fetched successfully",
  LINK_LIST_FETCHED_SUCCESSFULLY: "Link list fetched successfully",
  LINK_NOT_FOUND: "Link not found",
  LINK_STATUS_TOGGLED_SUCCESSFULLY: "Link status toggled successfully",
  LINK_IMAGE_REQUIRED: "Link image is required",
  // RetailerProductCatalog messages
  RETAILER_PRODUCT_CATALOG_CREATED_SUCCESSFULLY: "Retailer product catalog created successfully",
  RETAILER_PRODUCT_CATALOG_UPDATED_SUCCESSFULLY: "Retailer product catalog updated successfully",
  RETAILER_PRODUCT_CATALOG_DELETED_SUCCESSFULLY: "Retailer product catalog deleted successfully",
  RETAILER_PRODUCT_CATALOG_FETCHED_SUCCESSFULLY: "Retailer product catalog fetched successfully",
  RETAILER_PRODUCT_CATALOG_LIST_FETCHED_SUCCESSFULLY: "Retailer product catalog list fetched successfully",
  RETAILER_PRODUCT_CATALOG_NOT_FOUND: "Retailer product catalog not found",
  RETAILER_PRODUCT_CATALOG_STATUS_TOGGLED_SUCCESSFULLY: "Retailer product catalog status toggled successfully",
  RETAILER_PRODUCT_CATALOG_ATTACHMENT_REQUIRED: "Retailer product catalog attachment is required",
  // Story messages
  STORY_CREATED_SUCCESSFULLY: "Story created successfully",
  STORY_UPDATED_SUCCESSFULLY: "Story updated successfully",
  STORY_DELETED_SUCCESSFULLY: "Story deleted successfully",
  STORY_FETCHED_SUCCESSFULLY: "Story fetched successfully",
  STORY_LIST_FETCHED_SUCCESSFULLY: "Story list fetched successfully",
  STORY_NOT_FOUND: "Story not found",
  STORY_STATUS_TOGGLED_SUCCESSFULLY: "Story status toggled successfully",
  STORY_MEDIA_REQUIRED: "Story media file is required",
  // WebView messages
  WEBVIEW_CREATED_SUCCESSFULLY: "Web view image created successfully",
  WEBVIEW_UPDATED_SUCCESSFULLY: "Web view image updated successfully",
  WEBVIEW_DELETED_SUCCESSFULLY: "Web view image deleted successfully",
  WEBVIEW_FETCHED_SUCCESSFULLY: "Web view image fetched successfully",
  WEBVIEW_LIST_FETCHED_SUCCESSFULLY: "Web view image list fetched successfully",
  WEBVIEW_NOT_FOUND: "Web view image not found",
  WEBVIEW_IMAGE_REQUIRED: "Web view image is required",
  WEBVIEW_GROUPED_FETCHED_SUCCESSFULLY: "Web view images grouped by section fetched successfully",
}

export const AuthMessage = {
  LOGIN_SUCCESS: "Login Successfully",
  PROFILE_UPDATE: "Profile Update Successfully",
  REGISTER_SUCCESS: "Register Successfully",
  USER_NOT_FOUND: "User Not found",
  USER_ALREADY_EXISTS: "User already signUp please signIn",
  INVALID_CREDENTIALS: "Invalid email",
  OTP_NOT_MATCH: "OTP does not match",
  OTP_EXPIRED: "OTP Expired",
  OTP_SENT: "OTP sent successfully",
  LOGIN_FAILED: "Login failed",
  REGISTER_FAILED: "Registration failed",
  INVALID_PASS_EMAIL: "Invalid email or password",
  TOKEN_MISSING: "Authorization token missing or malformed",
  INVALID_TOKEN: "Invalid or expired token",
  INVALID_CURRENT_PASSWORD: "Current password is incorrect",
  PASSWORD_CHANGE: "Password updated successfully",
  UNAUTHORIZE: "Access denied. Unauthorized role.",
  FORGOT_EMAIL_SEND: "Check your inbox for the password reset link",
  CUSTOMER_NOT_ALLOW_BY_ADMIN: "Customer not allowed by admin",
  ERROR_IN_EMAIL: "Error sending email. Please try again later.",
  INVALID_EMAIL_FORMAT: "A valid email is required for login",
  DEVICE_NOT_ALLOWED_CONTACT_ADMIN: "Device not allowed. Please contact admin.",
  DEVICE_BLOCKED_BY_ADMIN: "This device is blocked by admin.",
  MISSING_DEVICE_FIELDS: "Missing required login/device fields",
  FILE_NOT_FOUND: "File not found",
  PASSWORD_NOT_SET: "Password not set for this retailer.",
  PASSWORD_INCORRECT: "Incorrect password.",
  PASSWORD_MISMATCH: "Confirm password does not match new password.",
  PASSWORD_ALREADY_USED: "The new password cannot be the same as the old password.",
  OLD_PASSWORD_INCORRECT: "Old password is incorrect.",
  PASSWORD_CHANGED: "Password changed successfully",
  UNAUTHORIZED: "Unauthorized access",
  LOGOUT_SUCCESS: "Logout successful",
};

export const SalesMessage = {
  PASSWORD_CHANGED: "Password changed successfully",
  PROFILE_UPDATED: "Profile updated successfully",
  OLD_NUMBER_SALES_NUMBER: "Order number and stop number are required.",
  NO_STOP_FOUND: "No stops found for the provided IDs.",
  NO_STOP: "No stops provided."
}
export const EmailMessage = {
  RESET_PASSWORD: " Password Reset Request",
  CLICK_LINK_RESET_PASSWORD: "Hi, click this link to reset your password",
  GET_STARTED: " Get Started – Your Access Credentials Inside",
  NEW_CREDENTIALS: "New Credentials"
}