import { ICustomerAttributes } from "../interfaces/customer.interface";

export const getDefaultCustomerValues = (UserID: number): Partial<ICustomerAttributes> => {
  const currentDate = new Date();

  return {
    C_SpecialTaxCode: "E",
    C_RetailCode: 0,
    C_StatementCode: 0,
    C_AuthorizedOnly: false,
    PriceLevel_Default: 0,
    NetCost_Flag: false,
    C_CashCustomer: false,
    C_Interest: 0,
    Interest_LastCharged: currentDate,
    ExpDate_SalesTax: currentDate,
    ExpDate_CigtTax: currentDate,
    C_Password: "",
    C_ChainStore: "",
    ExpDate_OtherTax: currentDate,
    C_StoreID: "",
    C_StoreIDQ: "",
    C_RetailRounding: "0123456789",
    C_DateCreated: currentDate,
    C_DateCreatedUser: UserID,
    C_DateModifed: currentDate,
    C_DateModifedUser: UserID,
    C_CommissionRate01_PCT: true,
    C_CommissionRate01: 0,
    C_CommissionRate02: 0,
    C_CommissionRate03: 0,
    C_CommissionRate04: 0,
    C_CommissionRate05: 0,
    C_CommissionRate06: 0,
    C_CommissionRate07: 0,
    C_CommissionRate08: 0,
    C_CommissionRate09: 0,
    C_CommissionRate10: 0,
    C_CommissionRate11: 0,
    C_CommissionRate12: 0,
    LastBalance: 0,
    LastInvoiceDate: currentDate,
    LastInvoiceNumber: 0,
    LastInvoiceAmount: 0,
    LastPaymentDate: currentDate,
    LastPaymentAmount: 0,
    LastPostDatedTotal: 0,
    WebHistory: 0,
    FTP_Host: "0",
    FTP_User: "0",
    FTP_Password: "0",
    FTP_Directory: "0",
    FTP_Protocol: 0,
    FTP_Mode: 0,
    FTP_FileExt: "0",
    ExpDate_OtherTax2: currentDate,
    ExpDate_OtherTax3: currentDate,
    MSA_StateTaxJurisdiction: "NA",
    C_PromotionGroup: "",
    C_AdminOnly: false,
    eCommerce_UpdateTag: true,
    eCommerce_FTP_HostID: 0,
    C_InputFormat: 0,
    C_InputFolder: "",
    C_StatementFormat: 0,
  };
};
